[build]
command = "pip install -r requirements.txt && uvicorn main:app"
publish = "."
functions = "api"

[build.environment]
PYTHON_VERSION = "3.9"

[[redirects]]
from = "/*"
to = "/.netlify/functions/api/:splat"
status = 200
